fail_fast: false
default_language_version:
  python: python3.8
repos:
  - repo: https://github.com/psf/black
    rev: "22.3.0"
    hooks:
    - id:  black

  - repo: https://github.com/pycqa/isort
    rev: "5.9.3"
    hooks:
      - id: isort
        name: isort (python)
      - id: isort
        name: isort (cython)
        types: [cython]
      - id: isort
        name: isort (pyi)
        types: [pyi]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.0.1"
    hooks:
    - id: trailing-whitespace
    - id: check-yaml
    - id: check-toml
    - id: check-ast

  - repo: https://github.com/pycqa/flake8
    rev: "3.9.0"
    hooks:
    - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.910"
    hooks:
    - id: mypy
      additional_dependencies: [types-requests, types-setuptools]
